@tool
## Updates the current generated by the solar panel based on the current time (hour), and updates
## the progress bar based on how close the current is to the maximum. Maximum current is reached for
## a short while before noon and lasts until a short while after.
class_name SynapseDemoUpdateSolarPanelCurrentFromHourBehavior
extends SynapseBehavior

@export var progress_bar: ProgressBar
@export var hour: SynapseFloatParameter
@export var max_current: SynapseFloatParameter
@export var current: SynapseFloatParameter

static func get_category() -> StringName:
	return SynapseBehavior.CATEGORY_DEMOS

func _unsuspend() -> void:
	progress_bar.min_value = 0.0

func _get_read_only_parameters() -> PackedStringArray:
	return ["hour", "max_current"]

func _get_signal_relays() -> Array[RuntimeSignalRelay]:
	return [
		SignalRelay.for_parameter(hour, _on_hour_value_set),
		SignalRelay.for_parameter(current, _on_current_value_set),
		SignalRelay.for_parameter(max_current, _on_max_current_value_set),
	]

func _process(_delta: float) -> void:
	if Engine.is_editor_hint():
		return

func _on_hour_value_set(new_value: float) -> void:
	var hour_angle := new_value / 24.0 * TAU
	var sun_height := sin(hour_angle - PI / 2.0)
	# 1.1 is an arbitrary multiplier to ensure we hit maximum current either side of noon
	current.value = minf(maxf(0.0, sun_height * max_current.value * 1.1), max_current.value)

func _on_current_value_set(new_value: float) -> void:
	progress_bar.value = new_value

func _on_max_current_value_set(new_value: float) -> void:
	progress_bar.max_value = new_value
